### ISSUE TITLE
DOMHelper issue

### ISSUE THREAD

**Issue by furley** [tildeio/ember-cli-fastboot#28] opened 2015-05-06 22:54 UTC
Not quite sure what this means.

```
$ DEBUG=ember-cli-fastboot:* ember fastboot
version: 0.2.3
Built project successfully. Stored in "dist".
  ember-cli-fastboot:ember-app app created; app=dist/assets/empart.js; vendor=dist/assets/vendor.js +0ms
  ember-cli-fastboot:ember-app vendor file evaluated +165ms
DEBUG: -------------------------------
DEBUG: Ember      : 1.13.0-beta.1+canary.d10d66e8
DEBUG: Ember Data : 1.0.0-beta.17+canary.51bac6a48b
DEBUG: -------------------------------
  ember-cli-fastboot:ember-app app file evaluated +13ms
Ember FastBoot running at http://:::3000

undefined:124
        var domHelper = new Ember.View.DOMHelper(doc);
                        ^
TypeError: undefined is not a function
    at Object.initialize (<anonymous>:124:25)
    at <anonymous>:14744:23
    at <anonymous>:14767:9
    at visit (<anonymous>:12712:7)
    at DAG.topsort (<anonymous>:12824:11)
    at Namespace.default.extend._runInitializer (<anonymous>:14766:13)
    at Namespace.default.extend.runInitializers (<anonymous>:14740:12)
    at Namespace.default.extend.boot (<anonymous>:14656:12)
    at Namespace.default.extend.domReady (<anonymous>:14640:12)
    at Queue.invoke (<anonymous>:11430:18)
```

**Comment by jimmyjamieson** [comment] 2015-05-11 17:02
Same issue here

**Comment by rwjblue** [comment] 2015-05-11 17:06
Canary has a few regressions related to Fastboot support (since Glimmer PR landing).  

I created https://github.com/emberjs/ember.js/issues/11115 upstream to track the issues in Ember itself.

**Comment by furley** [comment] 2015-05-11 17:12
Excellent. Thank you @rwjblue

**Comment by code0100fun** [comment] 2015-05-11 23:21
Would this just be changed to `var domHelper = new Ember.HTMLBars.DOMHelper(doc);`?

**Comment by rwjblue** [comment] 2015-05-12 00:19
@code0100fun - Yes, that is the first step, but there is more breakage after fixing that.

**Comment by rwjblue** [comment] 2015-05-12 00:23
@code0100fun - [These tests](https://github.com/emberjs/ember.js/blob/6af6fa4c6dd754fc722441602c1bc65a7e9359e0/tests/node/app-boot-test.js#L168-L240) will likely point the way to fixing in Ember itself (they are skipped for now, to land Glimmer so we can iterate with real user testing).

**Comment by rwjblue** [comment] 2015-05-24 02:25
Fixed by https://github.com/tildeio/ember-cli-fastboot/pull/35.  All credit goes to @code0100fun for tracking down the root issues, thank you!!

**Closed** 2015-05-24 02:25 UTC
